
import { GoogleGenAI } from "@google/genai";
import { SupportedLanguage, ImageSize } from "../types";

// In-memory cache for translations to avoid redundant API calls and improve speed
const translationCache = new Map<string, any>();

/**
 * Helper to extract JSON from a potentially markdown-wrapped string
 */
const extractJson = (text: string): string => {
  let cleanText = text.trim();
  // Remove markdown code blocks if present
  cleanText = cleanText.replace(/```json\n?|\n?```/g, '');
  // Find the first '{' and last '}' to handle any preamble/postscript text
  const firstBrace = cleanText.indexOf('{');
  const lastBrace = cleanText.lastIndexOf('}');
  
  if (firstBrace !== -1 && lastBrace !== -1) {
    return cleanText.substring(firstBrace, lastBrace + 1);
  }
  return cleanText;
};

/**
 * Translates site content dynamically using Gemini 3 Flash.
 * Optimized with caching and concise prompting for maximum performance.
 */
export const translateContent = async <T>(
  currentContent: T,
  targetLanguage: SupportedLanguage
): Promise<T> => {
  // Generate a cache key based on language and content fingerprint
  const contentString = JSON.stringify(currentContent);
  const cacheKey = `${targetLanguage}_${contentString.length}_${contentString.slice(0, 20)}`;
  
  if (translationCache.has(cacheKey)) {
    console.debug(`[Performance] Returning cached translation for ${targetLanguage}`);
    return translationCache.get(cacheKey);
  }

  // Always create a new GoogleGenAI instance right before making an API call
  const apiKey = process.env.API_KEY || process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.error("Gemini API key is not configured. Please set GEMINI_API_KEY in .env.local");
    throw new Error("API key not found");
  }
  const ai = new GoogleGenAI({ apiKey });

  // Use System Instruction for better role adherence
  const systemInstruction = `You are a professional translator for the Pacific American University School of Law website.
Your task is to translate the values of the provided JSON object into ${targetLanguage}.

Rules:
1. PRESERVE STRUCTURE: Do not change any keys in the JSON object. Return the exact same JSON structure.
2. PRESERVE NAMES: Do not translate proper names such as "Pacific American University", "Juris Doctor", "J.D.", "LL.M.", "Silicon Valley", "Westlaw", "LexisNexis", "Populi", or people's names.
3. PRESERVE HTML: If a value contains HTML tags (like <p>, <strong>, <ul>), keep the tags exactly as they are and only translate the text content inside them.
4. OUTPUT: Return ONLY the raw valid JSON string. Do not include markdown formatting (like \`\`\`json) or any conversational text.`;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: contentString,
      config: {
        systemInstruction: systemInstruction,
        responseMimeType: 'application/json',
        temperature: 0.1,
      }
    });

    const text = response.text;
    if (!text) throw new Error("No translation returned");
    
    // Robust extraction
    const cleanedJsonString = extractJson(text);
    
    const translated = JSON.parse(cleanedJsonString) as T;
    
    // Persist in memory cache
    translationCache.set(cacheKey, translated);
    
    return translated;
  } catch (error) {
    console.error("Translation error:", error);
    throw error;
  }
};

/**
 * Generates an architectural rendering using gemini-3-pro-image-preview.
 * This model supports 1K, 2K, and 4K resolutions and requires a user-selected API key.
 */
export const generateArchitecturalImage = async (
  prompt: string,
  size: ImageSize
): Promise<string> => {
  // Always create a new GoogleGenAI instance right before making an API call to ensure it uses the most up-to-date API key
  const apiKey = process.env.API_KEY || process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.error("Gemini API key is not configured. Please set GEMINI_API_KEY in .env.local");
    throw new Error("API key not found");
  }
  const ai = new GoogleGenAI({ apiKey });

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3-pro-image-preview',
      contents: {
        parts: [
          {
            text: prompt,
          },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: "16:9",
          imageSize: size as any, // "1K", "2K", or "4K"
        },
      },
    });

    const candidates = response.candidates;
    if (!candidates || candidates.length === 0 || !candidates[0].content?.parts) {
      throw new Error("No image was generated by the model.");
    }

    // Iterate through parts to find the image part as per guidelines
    for (const part of candidates[0].content.parts) {
      if (part.inlineData) {
        const base64EncodeString: string = part.inlineData.data;
        return `data:image/png;base64,${base64EncodeString}`;
      }
    }

    throw new Error("No image data found in the model response.");
  } catch (error) {
    console.error("Architectural generation error:", error);
    throw error;
  }
};
