/**
 * geminiService.ts
 *
 * Gemini API utilities — now used ONLY for:
 *   1. Translating individual news/notice items when saved by admin (stored in DB)
 *   2. Architectural image generation
 *
 * Static site content is pre-translated via scripts/generateLocales.ts
 * and served as JSON files from /public/locales/.
 */

import { GoogleGenAI } from "@google/genai";
import { SupportedLanguage, ImageSize } from "../types";
import { detectErrorType, ErrorType, getErrorMessage } from "../utils/errorMessages";
import { withRetry } from "../utils/apiHelpers";

const SUPPORTED_LANGUAGES: SupportedLanguage[] = [
  'Spanish', 'Korean', 'Chinese (Simplified)', 'Vietnamese', 'Japanese', 'French', 'Tagalog'
];

function getApiKey(): string {
  return (
    process.env.API_KEY ||
    process.env.GEMINI_API_KEY ||
    (typeof import.meta !== 'undefined' && import.meta.env?.VITE_GEMINI_API_KEY) ||
    ''
  );
}

function createClient(): GoogleGenAI {
  const apiKey = getApiKey();
  if (!apiKey || apiKey === 'undefined' || apiKey === 'null') {
    throw Object.assign(new Error('Gemini API key is not configured.'), {
      errorType: ErrorType.API_KEY_MISSING,
    });
  }
  return new GoogleGenAI({ apiKey });
}

/**
 * Translates a single news or notice item into all supported languages.
 * Returns a translations map: { Korean: {...}, Spanish: {...}, ... }
 *
 * Called by adminService when admin creates/updates a news or notice item.
 * Results are stored in the DB `translations` column so the frontend
 * never calls Gemini at runtime.
 */
export const translateNewsItem = async (
  item: { title: string; summary?: string; body?: string }
): Promise<Record<string, { title: string; summary?: string; body?: string }>> => {
  const ai = createClient();
  const results: Record<string, { title: string; summary?: string; body?: string }> = {};

  const translatableContent = {
    title: item.title,
    ...(item.summary ? { summary: item.summary } : {}),
    ...(item.body ? { body: item.body } : {}),
  };

  for (const lang of SUPPORTED_LANGUAGES) {
    try {
      const systemInstruction = `You are a professional translator for the Pacific American University School of Law website.
Translate the JSON values into ${lang}.
Rules:
1. Preserve JSON structure and all keys exactly.
2. Do NOT translate: "Pacific American University", "PAUSL", "J.D.", "LL.M.", "JD", "LLM", "Populi", "LSAT", "FYLSX", "State Bar of California".
3. Preserve HTML tags if present — only translate the text content inside them.
4. Return ONLY raw valid JSON.`;

      const response = await withRetry(
        async () =>
          ai.models.generateContent({
            model: 'gemini-3-flash-preview',
            contents: JSON.stringify(translatableContent),
            config: {
              systemInstruction,
              responseMimeType: 'application/json',
              temperature: 0.1,
            },
          }),
        { maxRetries: 2, initialDelay: 500, maxDelay: 3000, timeout: 20000 }
      );

      const text = response.text ?? '';
      const clean = text.replace(/```json\n?|\n?```/g, '').trim();
      const firstBrace = clean.indexOf('{');
      const lastBrace = clean.lastIndexOf('}');
      const jsonStr = firstBrace !== -1 ? clean.slice(firstBrace, lastBrace + 1) : clean;
      results[lang] = JSON.parse(jsonStr);
    } catch (err) {
      console.warn(`[Gemini] Failed to translate news item to ${lang}:`, err);
      // Skip this language — frontend falls back to English
    }
  }

  return results;
};


/**
 * Generates an architectural rendering using Gemini image generation.
 */
export const generateArchitecturalImage = async (
  prompt: string,
  size: ImageSize
): Promise<string> => {
  const ai = createClient();

  try {
    const response = await withRetry(
      async () =>
        ai.models.generateContent({
          model: 'gemini-3-pro-image-preview',
          contents: { parts: [{ text: prompt }] },
          config: {
            imageConfig: { aspectRatio: "16:9", imageSize: size },
          },
        }),
      { maxRetries: 3, initialDelay: 1000, maxDelay: 10000, timeout: 60000 }
    );

    const candidates = response.candidates;
    if (!candidates?.length || !candidates[0].content?.parts) {
      throw new Error("No image was generated by the model.");
    }

    for (const part of candidates[0].content.parts) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }

    throw new Error("No image data found in the model response.");
  } catch (error) {
    console.error("Architectural generation error:", error);
    const errorType = detectErrorType(error);
    const errorMessage = getErrorMessage(errorType, 'English');
    const enhancedError = new Error(errorMessage.message);
    (enhancedError as any).errorType = errorType;
    (enhancedError as any).title = errorMessage.title;
    (enhancedError as any).action = errorMessage.action;
    throw enhancedError;
  }
};
